### ISSUE TITLE
Sadly it doesn't work

### ISSUE THREAD

**Issue by Bazyliii** [RundownRhino/RegionScanner#1]
Processing region (0,-1).
PS E:\folder> E:\folder\region_scanner_v.0.1.2.exe --dims minecraft:overworld --path "E:\MultiMC\instances\Chocolate--\.minecraft\saves\New World"  --zone -1,1,-1,1

Starting to scan dimension: minecraft:overworld, at E:\MultiMC\instances\Chocolate--\.minecraft\saves\New World\region.
Processing region (-1,-1).
Processing region (-1,0).
Processing region (0,-1).
Processing region (0,0).
thread '<unnamed>' panicked at 'index out of bounds: the len is 4096 but the index is 4096', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\fastanvil-0.14.1\src\bits.rs:46:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'index out of bounds: the len is 4096 but the index is 4096', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\fastanvil-0.14.1\src\bits.rs:46:17
thread '<unnamed>' panicked at 'index out of bounds: the len is 4096 but the index is 4096', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\fastanvil-0.14.1\src\bits.rs:46:17
thread '<unnamed>' panicked at 'index out of bounds: the len is 4096 but the index is 4096', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\fastanvil-0.14.1\src\bits.rs:46:17
PS

That is what i have got in console

**Comment by alexschrod** [comment]
I've put up a release of the fix here while we wait for the author to accept my PR and release a new official release for anyone just wanting to get their JER data *now*: https://github.com/alexschrod/RegionScanner/releases/tag/0.1.2-stopgap

**Comment by RundownRhino** [comment]
Sorry, I missed this issue when it came out somehow, and only now noticed the PR. I'll try to find time to review the PR as soon as possible, and hopefully to work on the project some more, since there's actually people using it.
