### ISSUE TITLE
exe files missing

### ISSUE THREAD

**Issue by newyevon2** [RundownRhino/RegionScanner#14]
0.3.4 and 0.3.5 dont have exes available to download automatically

**Comment by RundownRhino** [comment]
What do you mean? They seem to be there in the releases.

**Comment by newyevon2** [comment]
> What do you mean? They seem to be there in the releases.

if i look at those two versions they only have .gz files to download. If i look at 0.3.3 it has a zip files to download with the exe inside of it

**Comment by RundownRhino** [comment]
Oh, you're right about all the archives being .tar.gz now. The windows ones still do contain the right executables, though.
![image](https://github.com/user-attachments/assets/9524da6c-0004-4471-a7f7-9b05e67f3bac)

**Comment by RundownRhino** [comment]
I can see how this happened though; I'll fix the workflow so that the windows archives are zips as they used to be.
