### ISSUE TITLE
No output folder generated

### ISSUE THREAD

**Issue by Lance-Terard** [RundownRhino/RegionScanner#17]
After running the program presumably successfully, given the follwing results:

 INFO  region_scanner > Elapsed: 5.61s, average of 0.62s per scanned region, or 1.11s per 1024 scanned chunks.
 INFO  region_scanner > Filtered results by normalized frequency. 384 block-dim pairs out of 483 were retained.
 
 An 'output' folder nor world-gen.json was generated in the same folder as region_scanner.exe, or any of the folders containing it.
 I ran CMD as admin and set region_scanner.exe as admin to hopefully fix it but to no avail. 
 
 I ran it with these instructions:
 D:\Minecraft_oregen_scanner\region_scanner.exe --path "C:\Users\lance\curseforge\minecraft\Instances\1.19.2 Zombie apocalypse (1)\saves\My survival" --dims minecraft:overworld minecraft:the_nether --proto include
 
 The world is 1.19.2, Forge verision 43.4.2

**Comment by Lance-Terard** [comment]
Never mind, I found it. It created the output in C:\Windows\System32\output for some reason.

**Comment by RundownRhino** [comment]
The output folder will get generated in the current working directory (you can see it in the prompt), not where the executable is. For an admin shell on Windows, the default working directory is `C:\Windows\System32`, so it makes sense that's where the second run made it. For a user shell, I think the default is your user's folder (e.g. `C:\Users\Lance-Terard`), so check there to find the output from your first run. In general, you can `cd` to whatever directory you want the output to be in before invoking the command.

Though really, I can see how always putting the output in CWD/output/world-gen.json is a bit silly. Perhaps I should add a CLI option to choose the output directory, and maybe start adding timestamps to the output files.

**Comment by RundownRhino** [comment]
Released v0.3.7 which makes it more clear where it writes files (and also allows specifying it with an option).

**Comment by RundownRhino** [comment]
(Oh, I can see now that the readme also falsely states the output folder will be whenever the executable is. Not sure how that happened - I've corrected this.)
