### ISSUE TITLE
Does not create 0% entires below the lowest found block

### ISSUE THREAD

**Issue by Garwinium** [RundownRhino/RegionScanner#8]
It seems that if this program finds a block at a certain Y level, but does not find any whatsoever at any Y level below that, then it will only make a json entry for that level, this results in odd slopes when a block is found at a high Y level and nowhere below it
![image](https://github.com/RundownRhino/RegionScanner/assets/92835818/8bef8228-bb8f-4082-96b8-61be424ee495)
![image](https://github.com/RundownRhino/RegionScanner/assets/92835818/9a294ab8-3c6c-4541-b852-1a31d7ec3f8a)
![image](https://github.com/RundownRhino/RegionScanner/assets/92835818/79822b9e-d227-4028-a25a-27a1a1480915)
![image](https://github.com/RundownRhino/RegionScanner/assets/92835818/e536fe4c-2f5f-4ca5-82e0-4adb9f3939c4)

**Comment by RundownRhino** [comment]
Good catch. In my option that's more JER's fault for drawing the plots like this (and in real usecases I filter the list of entries afterwards to remove those with too few blocks, so I don't get to see plots like these), but I can alter the output to make them look better.

**Comment by RundownRhino** [comment]
Whoops, I closed the wrong issue as completed.

**Comment by RundownRhino** [comment]
Now that I think of it, the current format of the distribution export was made specifically to address JER's plotting behaviour:
> distrib mentions all points from the lowest y-level the ore was found on to the highest, including zero frequencies. For example, above there's only two levels with jukeboxes founds on them, 39 and 48, yet the distribution mentions all levels between too. This is necessary to produce accurate JER plots, since it seems to just connect the points in order without assuming that unmentioned frequencies are zero.
so I guess something changed recently that broke it again.

**Comment by RundownRhino** [comment]
Should be fixed in v0.3.3.
