### ISSUE TITLE
Suggestion/feature request: Minimum amount to make an entry in the exported JSON file

### ISSUE THREAD

**Issue by Garwinium** [RundownRhino/RegionScanner#9]
example:
In the command line a argument could optionally be given for a minimum peak amount (say maybe 0.005%), and if there is no layer where the block occurs more then that then a entry will not be made in the JSON file for that block in that dimension.

This would be useful for filtering out blocks that only spawn in small amounts in structures like lightning rods and prismarine brick stairs for example.

**Comment by RundownRhino** [comment]
I'm not too sure what postprocessing I want to include into RegionScanner itself rather than leaving it to be done afterwards with, say, a python script. I might include some filters like this one, though.

**Comment by RundownRhino** [comment]
Done for v.0.3.2.

**Comment by Garwinium** [comment]
Cool, does it automatically do this now or do I have to specify a threshold in the command line arguments?

**Comment by RundownRhino** [comment]
> Cool, does it automatically do this now or do I have to specify a threshold in the command line arguments?

It's governed by a new CLI argument and is on by default.
